/**
 * Sticker collector for TeleBox-Next.
 * Saves replied stickers or images and supports per-chat batch collection.
 */

import { randomBytes } from 'node:crypto'
import * as fs from 'node:fs'
import * as path from 'node:path'
// @ts-expect-error -- provided by the TeleBox-Next host
import type { MessageContext } from '@mtcute/dispatcher'
// @ts-expect-error -- provided by the TeleBox-Next host
import { thtml as html, type Message, type TelegramClient } from '@mtcute/node'
// @ts-expect-error -- provided by the TeleBox-Next host
import { getErrorMessage } from '@utils/errorHelpers'
// @ts-expect-error -- provided by the TeleBox-Next host
import { htmlEscape } from '@utils/htmlEscape'
// @ts-expect-error -- provided by the TeleBox-Next host
import { createDirectoryInAssets } from '@utils/pathHelpers'
// @ts-expect-error -- provided by the TeleBox-Next host
import { Plugin, type PluginRuntimeContext } from '@utils/pluginBase'
// @ts-expect-error -- provided by the TeleBox-Next host
import { getPrefixes } from '@utils/pluginManager'
// @ts-expect-error -- provided by the TeleBox-Next host
import { tryGetCurrentRuntime } from '@utils/runtimeAccess'
// @ts-expect-error -- provided by the TeleBox-Next host
import { getGlobalClient } from '@utils/runtimeManager'
// @ts-expect-error -- provided by the TeleBox-Next host
import { safeGetReplyMessage } from '@utils/safeGetMessages'
// @ts-expect-error -- provided by the TeleBox-Next host
import sharp from 'sharp'

interface SaveStickerConfig {
  stickerSetShortName: string
  autoGenerated: boolean
}

interface BatchSession {
  active: boolean
  stopping: boolean
  startTime: number
  count: number
  stickerSetShortName: string
  generation: number
}

type StickerSourceMessage = Message | MessageContext

class StalePluginOperationError extends Error {}

const prefix = getPrefixes()[0] || '.'
const command = `${prefix}ss`
const STICKER_EMOJI = '⭐'
const MAX_STATIC_STICKER_BYTES = 512 * 1024
const STATIC_STICKER_QUALITIES = [90, 80, 70, 60, 50, 40, 30]

const getHelpText = (): string => `📌 <b>贴纸收藏插件</b>

<b>📝 功能：</b>
• 保存别人或自己发的贴纸到贴纸包
• 自动创建贴纸包（首次使用）
• 支持自定义贴纸包名称
• <b>批量模式</b>：可创建新贴纸包，也可使用固定贴纸包

<b>🔧 使用：</b>
• <code>${command}</code> - 回复贴纸/图片，保存到<b>固定贴纸包</b>
• <code>${command} start</code> - 开始批量收集（需回复第一张贴纸/图片）
• <code>${command} start fixed</code> - 使用固定贴纸包开始批量收集
• <code>${command} start &lt;ID&gt;</code> - 添加到指定贴纸包并开始批量收集
• <code>${command} stop</code> - 结束批量收集
• <code>${command} set &lt;名称&gt;</code> - 设置<b>固定贴纸包</b>名称
• <code>${command} show</code> - 查看当前配置
• <code>${command} reset</code> - 重置固定贴纸包
• <code>${command} help</code> - 显示帮助

<b>📌 说明：</b>
• 批量模式按聊天分别管理
• 贴纸包名称只能包含字母、数字和下划线
• 图片会自动转换为 512x512 的 WebP 贴纸格式`

const isValidStickerSetName = (value: string): boolean => /^[a-zA-Z0-9_]{3,64}$/.test(value)

const isSupportedMedia = (message: StickerSourceMessage): boolean => {
  const media = message.media
  if (!media) return false
  if (media.type === 'photo' || media.type === 'sticker') return true
  if (media.type === 'video') return media.isLegacyGif
  if (media.type !== 'document') return false

  const mimeType = media.mimeType || ''
  const fileName = media.fileName || ''
  return mimeType.startsWith('image/') || /\.(?:jpe?g|png|webp|gif|bmp|tiff?|avif|heic|heif)$/i.test(fileName)
}

class SaveStickerPlugin extends Plugin {
  description = (): string => `\n保存贴纸和图片到个人贴纸包\n\n${getHelpText()}`

  private config: SaveStickerConfig | null = null
  private configPath = ''
  private abortSignal?: AbortSignal
  private lifecycle?: PluginRuntimeContext['lifecycle']
  private generation = 0
  private readonly batchSessions = new Map<string, BatchSession>()
  private readonly startingSessions = new Map<string, symbol>()
  private readonly processingQueues = new Map<string, Promise<void>>()
  private readonly processingMessageIds = new Set<string>()

  listenMessageHandlerIgnoreEdited = true
  listenMessageHandler = async (msg: MessageContext, options?: { isEdited?: boolean }): Promise<void> => {
    const meId = tryGetCurrentRuntime()?.meId
    const isSavedMessage = meId != null && String(msg.chat.id) === meId
    if (options?.isEdited || (!msg.isOutgoing && !isSavedMessage) || !isSupportedMedia(msg)) return

    const sessionId = this.getSessionId(msg)
    const session = this.batchSessions.get(sessionId)
    if (!session?.active || session.stopping || session.generation !== this.generation || this.abortSignal?.aborted) return

    const dedupeKey = this.getMessageDedupeKey(msg)
    if (this.processingMessageIds.has(dedupeKey)) return
    this.processingMessageIds.add(dedupeKey)
    this.lifecycle?.setTimeout(
      () => {
        this.processingMessageIds.delete(dedupeKey)
      },
      10 * 60 * 1000,
      { label: 'save-sticker:dedupe-expiry' }
    )

    const previous = this.processingQueues.get(sessionId) ?? Promise.resolve()
    const current = previous
      .catch(() => undefined)
      .then(async () => {
        if (session.generation !== this.generation || this.abortSignal?.aborted) return
        if (this.lifecycle) {
          await this.lifecycle.runTask(() => this.processBatchMessage(msg, session), { label: `save-sticker:batch:${sessionId}` })
        } else {
          await this.processBatchMessage(msg, session)
        }
      })
      .finally(() => {
        if (this.processingQueues.get(sessionId) === current) this.processingQueues.delete(sessionId)
      })

    this.processingQueues.set(sessionId, current)
    await current
  }

  setup(context: PluginRuntimeContext): void {
    this.generation = context.generation
    this.lifecycle = context.lifecycle
    this.abortSignal = context.signal
    this.ensureConfig()
  }

  cleanup(): void {
    for (const session of this.batchSessions.values()) session.active = false
    this.generation += 1
    this.abortSignal = undefined
    this.lifecycle = undefined
    this.batchSessions.clear()
    this.startingSessions.clear()
    this.processingQueues.clear()
    this.processingMessageIds.clear()
    this.config = null
    this.configPath = ''
  }

  private getSessionId(msg: StickerSourceMessage): string {
    return `${String(msg.chat.id)}_${String(msg.sender.id)}`
  }

  private getMessageDedupeKey(msg: StickerSourceMessage): string {
    return `${String(msg.chat.id)}_${msg.id}`
  }

  private isRuntimeCurrent(generation: number, signal?: AbortSignal): boolean {
    return generation === this.generation && !signal?.aborted
  }

  private isCurrentSession(sessionId: string, session: BatchSession): boolean {
    return session.active && session.generation === this.generation && this.batchSessions.get(sessionId) === session && !this.abortSignal?.aborted
  }

  private assertOperationCurrent(isCurrent: () => boolean): void {
    if (!isCurrent()) throw new StalePluginOperationError()
  }

  private ensureConfig(): SaveStickerConfig {
    if (!this.configPath) {
      this.configPath = path.join(createDirectoryInAssets('save_sticker'), 'config.json')
    }

    if (!fs.existsSync(this.configPath)) {
      this.config = { stickerSetShortName: '', autoGenerated: false }
      this.saveConfig()
      return this.config
    }

    try {
      const parsed: unknown = JSON.parse(fs.readFileSync(this.configPath, 'utf8'))
      if (parsed && typeof parsed === 'object' && 'stickerSetShortName' in parsed && typeof parsed.stickerSetShortName === 'string' && 'autoGenerated' in parsed && typeof parsed.autoGenerated === 'boolean') {
        this.config = {
          stickerSetShortName: parsed.stickerSetShortName,
          autoGenerated: parsed.autoGenerated
        }
      } else {
        this.config = { stickerSetShortName: '', autoGenerated: false }
      }
    } catch (error: unknown) {
      console.error('[save_sticker] Failed to load config:', error)
      this.config = { stickerSetShortName: '', autoGenerated: false }
    }

    return this.config
  }

  private saveConfig(): void {
    const config = this.config ?? { stickerSetShortName: '', autoGenerated: false }
    if (!this.configPath) {
      this.configPath = path.join(createDirectoryInAssets('save_sticker'), 'config.json')
    }
    fs.writeFileSync(this.configPath, JSON.stringify(config, null, 2), 'utf8')
  }

  private ensureStickerSetName(): string {
    const config = this.ensureConfig()
    if (!config.stickerSetShortName) {
      config.stickerSetShortName = `tb_${randomBytes(4).toString('hex')}`
      config.autoGenerated = true
      this.saveConfig()
    }
    return config.stickerSetShortName
  }

  private async convertToStaticSticker(source: Buffer): Promise<Buffer> {
    const image = sharp(source)
      .rotate()
      .resize(512, 512, {
        fit: 'contain',
        background: { r: 0, g: 0, b: 0, alpha: 0 }
      })

    for (const quality of STATIC_STICKER_QUALITIES) {
      const sticker = await image.clone().webp({ quality }).toBuffer()
      if (sticker.length <= MAX_STATIC_STICKER_BYTES) return sticker
    }

    throw new Error('图片转换后仍超过 Telegram 静态贴纸 512 KB 限制')
  }

  private async prepareStickerFile(client: TelegramClient, message: StickerSourceMessage, isCurrent: () => boolean): Promise<string> {
    const media = message.media
    if (!media || !isSupportedMedia(message)) throw new Error('请回复贴纸或图片')
    if (media.type === 'sticker') {
      if (media.stickerType === 'sticker') return media.fileId
      if (media.sourceType !== 'static') throw new Error('暂不支持把动画面具贴纸或动态自定义表情转换到普通贴纸包')
    }

    const source = Buffer.from(await client.downloadAsBuffer(media))
    this.assertOperationCurrent(isCurrent)
    if (source.length === 0) throw new Error('下载图片失败')
    const sticker = await this.convertToStaticSticker(source)
    this.assertOperationCurrent(isCurrent)

    // mtcute 0.31 treats a raw Buffer passed to add/create as a generic document.
    // Pre-upload it as sticker media so Telegram receives the WebP MIME and sticker attributes.
    const uploaded = await client.uploadMedia({
      type: 'sticker',
      file: sticker,
      fileName: 'sticker.webp',
      fileMime: 'image/webp',
      alt: STICKER_EMOJI
    })
    this.assertOperationCurrent(isCurrent)
    if (uploaded.type !== 'sticker') throw new Error('Telegram 未将上传文件识别为静态贴纸')
    return uploaded.fileId
  }

  private async stickerSetExists(client: TelegramClient, shortName: string): Promise<boolean> {
    try {
      await client.getStickerSet(shortName)
      return true
    } catch (error: unknown) {
      if (getErrorMessage(error).includes('STICKERSET_INVALID')) return false
      throw error
    }
  }

  private async saveToStickerSet(client: TelegramClient, shortName: string, source: StickerSourceMessage, createIfMissing: boolean, isCurrent: () => boolean): Promise<'created' | 'added'> {
    const file = await this.prepareStickerFile(client, source, isCurrent)
    this.assertOperationCurrent(isCurrent)
    const exists = await this.stickerSetExists(client, shortName)
    this.assertOperationCurrent(isCurrent)

    if (exists) {
      await client.addStickerToSet(shortName, { file, emojis: STICKER_EMOJI })
      this.assertOperationCurrent(isCurrent)
      return 'added'
    }
    if (!createIfMissing) throw new Error('STICKERSET_INVALID')

    await client.createStickerSet({
      owner: 'self',
      title: shortName,
      shortName,
      type: 'sticker',
      stickers: [{ file, emojis: STICKER_EMOJI }]
    })
    this.assertOperationCurrent(isCurrent)
    return 'created'
  }

  private async handleSet(msg: MessageContext, args: string[]): Promise<void> {
    const name = args.join('_').replace(/[^a-zA-Z0-9_]/g, '')
    if (!isValidStickerSetName(name)) {
      await msg.edit({ text: `❌ 贴纸包名称必须为 3-64 个字母、数字或下划线\n\n用法: ${command} set <名称>` })
      return
    }

    const config = this.ensureConfig()
    config.stickerSetShortName = name
    config.autoGenerated = false
    this.saveConfig()
    await msg.edit({ text: html(`✅ 固定贴纸包已设置为 <code>${htmlEscape(name)}</code>\n\nt.me/addstickers/${htmlEscape(name)}`) })
  }

  private async handleShow(msg: MessageContext): Promise<void> {
    const config = this.ensureConfig()
    const session = this.batchSessions.get(this.getSessionId(msg))
    const name = config.stickerSetShortName || '未设置（首次保存时自动生成）'
    const auto = config.autoGenerated ? '（自动生成）' : ''
    const batch = session?.active ? `\n\n🔄 <b>批量收集：</b>进行中\n• 贴纸包: <code>${htmlEscape(session.stickerSetShortName)}</code>\n• 已收集: ${session.count} 个` : ''
    await msg.edit({ text: html(`📌 <b>贴纸收藏配置</b>\n\n<b>固定贴纸包:</b> <code>${htmlEscape(name)}</code> ${auto}${batch}`) })
  }

  private async handleStart(msg: MessageContext, args: string[]): Promise<void> {
    const sessionId = this.getSessionId(msg)
    if (this.startingSessions.has(sessionId)) {
      await msg.edit({ text: '⏳ 正在启动批量收集，请稍候…' })
      return
    }

    const startToken = Symbol(sessionId)
    this.startingSessions.set(sessionId, startToken)
    try {
      await this.startBatchSession(msg, args)
    } finally {
      if (this.startingSessions.get(sessionId) === startToken) this.startingSessions.delete(sessionId)
    }
  }

  private async startBatchSession(msg: MessageContext, args: string[]): Promise<void> {
    const generation = this.generation
    const signal = this.abortSignal
    const sessionId = this.getSessionId(msg)
    const active = this.batchSessions.get(sessionId)
    if (active?.active) {
      await msg.edit({ text: html(`⚠️ 批量收集已在进行中\n\n贴纸包: <code>${htmlEscape(active.stickerSetShortName)}</code>\n已收集: ${active.count} 个`) })
      return
    }

    const client = await getGlobalClient()
    if (!this.isRuntimeCurrent(generation, signal)) return
    const replied = await safeGetReplyMessage(msg)
    if (!this.isRuntimeCurrent(generation, signal)) return
    const requested = (args[0] || '').trim()
    const useFixed = ['fixed', '固定'].includes(requested.toLowerCase())
    let shortName: string
    let createIfMissing = false

    if (useFixed) {
      shortName = this.ensureStickerSetName()
      createIfMissing = true
    } else if (requested) {
      shortName = requested.replace(/[^a-zA-Z0-9_]/g, '')
      if (!isValidStickerSetName(shortName)) {
        await msg.edit({ text: '❌ 贴纸包名称必须为 3-64 个字母、数字或下划线' })
        return
      }
      const requestedSetExists = await this.stickerSetExists(client, shortName)
      if (!this.isRuntimeCurrent(generation, signal)) return
      if (!requestedSetExists) {
        await msg.edit({ text: html(`❌ 贴纸包 <code>${htmlEscape(shortName)}</code> 不存在`) })
        return
      }
    } else {
      shortName = `tb_batch_${randomBytes(4).toString('hex')}`
      createIfMissing = true
    }

    let count = 0
    const exists = await this.stickerSetExists(client, shortName)
    if (!this.isRuntimeCurrent(generation, signal)) return
    if (!exists && (!replied || !isSupportedMedia(replied))) {
      await msg.edit({ text: html(`❌ 请回复贴纸或图片来创建新贴纸包\n\n用法: <code>${command} start</code>`) })
      return
    }

    if (replied && isSupportedMedia(replied)) {
      await msg.edit({ text: exists ? '⏳ 正在添加到贴纸包…' : '⏳ 正在创建新贴纸包…' })
      if (!this.isRuntimeCurrent(generation, signal)) return
      await this.saveToStickerSet(client, shortName, replied, createIfMissing, () => this.isRuntimeCurrent(generation, signal))
      if (!this.isRuntimeCurrent(generation, signal)) return
      count = 1
    }

    if (!this.isRuntimeCurrent(generation, signal)) return
    const session: BatchSession = {
      active: true,
      stopping: false,
      startTime: Date.now(),
      count,
      stickerSetShortName: shortName,
      generation
    }
    this.batchSessions.set(sessionId, session)

    if (!this.isCurrentSession(sessionId, session)) return
    await msg.edit({
      text: html(`🎯 <b>批量收集模式已开启</b>\n\n📦 贴纸包: <code>${htmlEscape(shortName)}</code>\n🔗 t.me/addstickers/${htmlEscape(shortName)}${count ? '\n✅ 第一个贴纸已保存' : ''}\n\n继续发送图片或贴纸，使用 <code>${command} stop</code> 结束`)
    })
  }

  private async handleStop(msg: MessageContext): Promise<void> {
    const sessionId = this.getSessionId(msg)
    const session = this.batchSessions.get(sessionId)
    if (!session?.active) {
      await msg.edit({ text: html(`❌ 批量收集模式未开启\n\n使用 <code>${command} start</code> 开始`) })
      return
    }

    if (session.stopping) {
      await msg.edit({ text: '⏳ 正在等待当前媒体处理完成…' })
      return
    }

    session.stopping = true
    await this.processingQueues.get(sessionId)?.catch(() => undefined)
    if (!this.isCurrentSession(sessionId, session)) return
    session.active = false
    this.batchSessions.delete(sessionId)
    const seconds = Math.floor((Date.now() - session.startTime) / 1000)
    await msg.edit({ text: html(`✅ <b>批量收集已结束</b>\n\n• 收集贴纸: ${session.count} 个\n• 用时: ${seconds} 秒\n• 贴纸包: <code>${htmlEscape(session.stickerSetShortName)}</code>\n• 链接: t.me/addstickers/${htmlEscape(session.stickerSetShortName)}`) })
  }

  private async handleSave(msg: MessageContext): Promise<void> {
    const generation = this.generation
    const signal = this.abortSignal
    const replied = await safeGetReplyMessage(msg)
    if (!this.isRuntimeCurrent(generation, signal)) return
    const target = replied ?? msg
    if (!isSupportedMedia(target)) {
      await msg.edit({ text: html(`❌ 请回复贴纸或图片\n\n使用方法: 回复媒体后发送 <code>${command}</code>`) })
      return
    }

    const shortName = this.ensureStickerSetName()
    await msg.edit({ text: '⏳ 正在保存…' })
    if (!this.isRuntimeCurrent(generation, signal)) return
    const client = await getGlobalClient()
    if (!this.isRuntimeCurrent(generation, signal)) return
    const result = await this.saveToStickerSet(client, shortName, target, true, () => this.isRuntimeCurrent(generation, signal))
    if (!this.isRuntimeCurrent(generation, signal)) return
    await msg.edit({ text: html(`✅ 已${result === 'created' ? '创建贴纸包并保存' : '保存到固定贴纸包'}\n\n📦 <code>${htmlEscape(shortName)}</code>\n🔗 t.me/addstickers/${htmlEscape(shortName)}`) })
  }

  private async processBatchMessage(msg: MessageContext, session: BatchSession): Promise<void> {
    const sessionId = this.getSessionId(msg)
    if (!this.isCurrentSession(sessionId, session)) return
    const client = await getGlobalClient()
    if (!this.isCurrentSession(sessionId, session)) return
    const notice = await msg.replyText(`⏳ 处理中... (${session.count + 1})`)

    try {
      if (!this.isCurrentSession(sessionId, session)) {
        await client.deleteMessagesById(notice.chat.id, [notice.id], { revoke: true }).catch(() => undefined)
        return
      }

      await this.saveToStickerSet(client, session.stickerSetShortName, msg, false, () => this.isCurrentSession(sessionId, session))
      if (!this.isCurrentSession(sessionId, session)) {
        await client.deleteMessagesById(notice.chat.id, [notice.id], { revoke: true }).catch(() => undefined)
        return
      }
      session.count += 1
      await client.deleteMessagesById(msg.chat.id, [msg.id], { revoke: true }).catch(() => undefined)
      await client.editMessage({
        chatId: notice.chat.id,
        message: notice.id,
        text: `✅ 已保存第 ${session.count} 个`
      })
      this.lifecycle?.setTimeout(
        () => {
          void client.deleteMessagesById(notice.chat.id, [notice.id], { revoke: true }).catch(() => undefined)
        },
        2000,
        { label: 'save-sticker:delete-status' }
      )
    } catch (error: unknown) {
      if (error instanceof StalePluginOperationError || !this.isCurrentSession(sessionId, session)) {
        await client.deleteMessagesById(notice.chat.id, [notice.id], { revoke: true }).catch(() => undefined)
        return
      }
      console.error('[save_sticker] Batch save failed:', error)
      await client
        .editMessage({
          chatId: notice.chat.id,
          message: notice.id,
          text: html(`❌ 保存失败: ${htmlEscape(getErrorMessage(error))}`)
        })
        .catch(() => undefined)
    }
  }

  private async handleCommand(msg: MessageContext): Promise<void> {
    const generation = this.generation
    const signal = this.abortSignal
    const args = (msg.text ?? '').trim().split(/\s+/).slice(1)
    const subcommand = args[0]?.toLowerCase()

    try {
      if (subcommand === 'help' || subcommand === 'h') {
        await msg.edit({ text: html(getHelpText()) })
      } else if (subcommand === 'set') {
        await this.handleSet(msg, args.slice(1))
      } else if (subcommand === 'show' || subcommand === 'config') {
        await this.handleShow(msg)
      } else if (subcommand === 'reset') {
        this.config = { stickerSetShortName: '', autoGenerated: false }
        this.saveConfig()
        await msg.edit({ text: '✅ 已重置固定贴纸包配置' })
      } else if (subcommand === 'start') {
        await this.handleStart(msg, args.slice(1))
      } else if (subcommand === 'stop') {
        await this.handleStop(msg)
      } else {
        await this.handleSave(msg)
      }
    } catch (error: unknown) {
      if (error instanceof StalePluginOperationError || !this.isRuntimeCurrent(generation, signal)) return
      console.error('[save_sticker] Execution failed:', error)
      const errorMessage = getErrorMessage(error)
      let response = `❌ 操作失败: ${htmlEscape(errorMessage)}`
      if (errorMessage.includes('STICKERS_TOO_MUCH')) {
        response = '❌ 贴纸包已满'
      } else if (errorMessage.includes('STICKER_FILE_INVALID')) {
        response = '❌ 贴纸文件无效，请确认它是有效的图片或普通贴纸'
      } else if (errorMessage.includes('STICKERSET_INVALID')) {
        response = '❌ 贴纸包名称无效'
      }
      await msg.edit({ text: html(response) }).catch(() => undefined)
    }
  }

  cmdHandlers: Record<string, (msg: MessageContext, trigger?: MessageContext) => Promise<void>> = {
    save_sticker: async (msg) => this.handleCommand(msg),
    ss: async (msg) => this.handleCommand(msg)
  }
}

export default new SaveStickerPlugin()
